title: Rebecca Moore's Homepage
page-top-title: Computer Science PhD student
top-section-bg-text: Rebecca Moore
home-subtitle: Rebecca Moore
copyright-text: '&copy; Rebecca Moore 2023. All Rights Reserved.'
