
title: Rebecca Moore's Homepage
page-top-title: Rebecca Moore
top-section-bg-text: Rebecca Moore
home-subtitle: Computer Science PhD student
copyright-text: '&copy; Rebecca Moore 2023. All Rights Reserved.'
